#!/bin/bash

if [ "$1" != "" ]; then
    echo "Mode: " $1 
else
    echo "Please introduce the mode that will be used"
    exit 1
fi

if [ "$2" != "" ]; then
    echo "MQTT topic: " $2 
else
    echo "Please introduce the topic that will be used"
    exit 1
fi

if [ "$3" != "" ]; then
    echo "Kafka Broker: " $3 
else
    echo "Please introduce the Kafka broker <address>:<port>"
    exit 1
fi

if [ "$4" != "" ]; then
    echo "Zookeeper Server: " $4 
else
    echo "Please introduce the Zookeeper Server <address>:<port>"
fi

if [ "$5" != "" ]; then
    echo "MQTT port: " $5
else
    echo "Please introduce the MQTT port"
    exit 1
fi

if [ "$1" == "in" ]; then
	sleep 30
	./kafka_2.12-2.5.0/bin/kafka-topics.sh --create --zookeeper $4 --replication-factor 3 --partitions 1 --topic $2	
	(mosquitto -p $5 -c mosquitto-local.conf) & (mosquitto_sub -q 2 -t iot -h localhost -p 1883 | ./Kafka-proxy/kafka-proxy $1 $3 $2)
fi

if [ "$1" == "out" ]; then
	sleep 30
	./kafka_2.12-2.5.0/bin/kafka-topics.sh --create --zookeeper $4 --replication-factor 3 --partitions 1 --topic $2
	(mosquitto -p $5 -c mosquitto-local.conf) & (./Kafka-proxy/kafka-proxy $1 $3 $2)
fi

if [ "$1" != "in" ] && [ "$1" != "out" ]; then
	echo "Service not configured for input or output"
	echo ""
	echo "USAGE: start-proxy in|out <MQTT broker> <MQTT topic> <Kafka broker> <Zookeeper Server>"
	echo "./start-proxy in <address>:<port> <topic> <address>:<port> <address>:<port>"
	echo ""
	echo "USAGE: start-proxy in|out <MQTT broker> <MQTT topic> <Kafka broker>"
	echo "./start-proxy out <address>:<port> <topic> <address>:<port> <mqtt port> "
fi
