apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: coap
    name: coap-cs
  spec:
    clusterIP: None
    type: LoadBalancer
    ports:
    - name: clientinudp
      port: 5683
      protocol: UDP
      targetPort: 5683
    - name: clientintcp
      port: 5683
      protocol: TCP
      targetPort: 5683
    selector:
      app: coap
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: coap-deployment
    labels:
      app: coap
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: coap
    template:
      metadata:
        labels:
          app: coap
      spec:
        containers:
         - name: coap
           command:
           - sh
           - -c
           #- tail -f /dev/null
           - "./start-coap-rep3 iot kafka-hs.kafka.svc.cluster.local:9093 zk-cs.kafka.svc.cluster.local:2181"
           image: josesoares/proxy
           ports:
           - containerPort: 5683
kind: List
metadata: {}