apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: mosquitto-out
    name: mosquitto-cs-out
  spec:
    clusterIP: None
    type: LoadBalancer
    ports:
    - name: clientout
      port: 1884
      protocol: TCP
      targetPort: 1884
    - name: gwsocket
      port: 7000
      protocol: TCP
      targetPort: 7000
    selector:
      app: mosquitto-out
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mosquitto-deployment-out
    labels:
      app: mosquitto-out
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mosquitto-out
    template:
      metadata:
        labels:
          app: mosquitto-out
      spec:
        containers:
         - name: mosquitto-out
           command:
           - sh
           - -c
           - "  echo 'set_tcp_nodelay true' >> mosquitto-local.conf; \
    echo 'user mosquitto' >> mosquitto-local.conf; \
    echo 'persistence true' >> mosquitto-local.conf; \
    echo 'max_inflight_messages 1' >> mosquitto-local.conf;  \
    echo 'max_queued_messages 10' >> mosquitto-local.conf;  \
    echo 'autosave_interval 1800' >> mosquitto-local.conf;  \
    ./start-mqtt-rep3 out iot kafka-hs.kafka.svc.cluster.local:9093 zk-cs.kafka.svc.cluster.local:2181 1884"
           image: josesoares/proxy
           ports:
           - containerPort: 1884
kind: List
metadata: {}
